"""initial schema

Revision ID: 8fcbeeb914f4
Revises:
Create Date: 2026-07-09 21:23:00.963359

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401 — AutoString column type

from alembic import op

revision = "8fcbeeb914f4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athlete_measurements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_user_id", sa.Integer(), nullable=True),
        sa.Column("measured_at", sa.DateTime(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("muscle_kg", sa.Float(), nullable=True),
        sa.Column("fat_kg", sa.Float(), nullable=True),
        sa.Column("body_fat_pct", sa.Float(), nullable=True),
        sa.Column("visceral_fat", sa.Float(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_athlete_measurements_measured_at"),
        "athlete_measurements",
        ["measured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_athlete_measurements_source"), "athlete_measurements", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_athlete_measurements_telegram_user_id"),
        "athlete_measurements",
        ["telegram_user_id"],
        unique=False,
    )
    op.create_table(
        "athlete_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("telegram_user_id", sa.Integer(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("goal", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("experience_level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("training_days_per_week", sa.Integer(), nullable=True),
        sa.Column("usual_session_minutes", sa.Integer(), nullable=True),
        sa.Column("injuries", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("limitations", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("preferred_exercises", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("disliked_exercises", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("gym_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("available_equipment", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("unavailable_equipment", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("onboarding_complete", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_athlete_profiles_telegram_user_id"),
        "athlete_profiles",
        ["telegram_user_id"],
        unique=False,
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("muscle_group", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("secondary_muscles", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body_part", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("equipment", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instructions_es", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("gif_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exercises_body_part"), "exercises", ["body_part"], unique=False)
    op.create_index(op.f("ix_exercises_equipment"), "exercises", ["equipment"], unique=False)
    op.create_index(op.f("ix_exercises_external_id"), "exercises", ["external_id"], unique=True)
    op.create_index(op.f("ix_exercises_muscle_group"), "exercises", ["muscle_group"], unique=False)
    op.create_index(op.f("ix_exercises_name"), "exercises", ["name"], unique=False)
    op.create_index(op.f("ix_exercises_target"), "exercises", ["target"], unique=False)
    op.create_table(
        "workout_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("goal", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("energy", sa.Integer(), nullable=False),
        sa.Column("discomfort", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration_estimated", sa.Integer(), nullable=False),
        sa.Column("duration_actual", sa.Integer(), nullable=False),
        sa.Column("feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("coach_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("share_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("telegram_user_id", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workout_sessions_session_date"), "workout_sessions", ["session_date"], unique=False
    )
    op.create_index(
        op.f("ix_workout_sessions_telegram_user_id"),
        "workout_sessions",
        ["telegram_user_id"],
        unique=False,
    )
    op.create_table(
        "planned_exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("target_sets", sa.Integer(), nullable=False),
        sa.Column("target_reps", sa.Integer(), nullable=False),
        sa.Column("suggested_weight", sa.Float(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["workout_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "performed_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("planned_exercise_id", sa.Integer(), nullable=False),
        sa.Column("set_number", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("rpe", sa.Float(), nullable=True),
        sa.Column("sensation", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["planned_exercise_id"],
            ["planned_exercises.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("performed_sets")
    op.drop_table("planned_exercises")
    op.drop_index(op.f("ix_workout_sessions_telegram_user_id"), table_name="workout_sessions")
    op.drop_index(op.f("ix_workout_sessions_session_date"), table_name="workout_sessions")
    op.drop_table("workout_sessions")
    op.drop_index(op.f("ix_exercises_target"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_name"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_muscle_group"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_external_id"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_equipment"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_body_part"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_index(op.f("ix_athlete_profiles_telegram_user_id"), table_name="athlete_profiles")
    op.drop_table("athlete_profiles")
    op.drop_index(
        op.f("ix_athlete_measurements_telegram_user_id"), table_name="athlete_measurements"
    )
    op.drop_index(op.f("ix_athlete_measurements_source"), table_name="athlete_measurements")
    op.drop_index(op.f("ix_athlete_measurements_measured_at"), table_name="athlete_measurements")
    op.drop_table("athlete_measurements")
    # ### end Alembic commands ###
